### ISSUE TITLE
Send Docker container's logs to Logstash

### ISSUE THREAD

**Issue by jmarin** [cfpb/grasshopper#101]
The logback-logstash integration is JVM specific (i.e. won't work for other tech) and has been somewhat flaky at times. It also uses TCP which might affect performance of the running application. Explore ways to send logs from running Docker container to Logstash. At the same time, review codebase to standardize and increase logging

**Comment by hkeeler** [comment]
Renaming this to "Send Docker container's logs to Logstash".  I think the _review codebase to standardize and increase logging_ is covered by #105.

**Comment by hkeeler** [comment]
I've been working though Nathan LeClaire's [Automating Docker Logging: ElasticSearch, Logstash, Kibana, and Logspout](http://nathanleclaire.com/blog/2015/04/27/automating-docker-logging-elasticsearch-logstash-kibana-and-logspout/) post.  Here's the TL;DR:

``` bash
# Upgrade docker-compose to 1.2.0.  Necessary to support `extends` in compose yaml files
brew update
brew upgrade docker-compose

# Checkout his canned ELK/Logspout setup
git clone https://github.com/nathanleclaire/elk nathanleclaire-elk

# Launch it
cd nathanleclaire-elk
docker-compose up
```

...then browse to the following:

| Service | URL |
| --- | --- |
| Kibana | http://{{boot2docker-ip}} |
| Elasticsearch | http://{{boot2docker-ip}}:9200 |
| cAdvisor | http://{{boot2docker-ip}}:8080 |

I'll be continuing to work through this post, and then try to merge a _hopefully_ simpler version into our Docker Compose setup.

**Comment by hkeeler** [comment]
I've been reading through [Centralized System and Docker Logging with ELK Stack](http://technologyconversations.com/2015/05/18/centralized-system-and-docker-logging-with-elk-stack), which takes the approach we've been discussed:
1. Run an `rsyslog` service...somewhere.
2. Run each Docker containers with `--log-driver syslog`, sending logs to `syslog` instead of `stdout`.
3. `rsyslog` forwards to Logstash.
4. Logstash writes to Elasticsearch

The piece of this puzzle I didn't completely understand is that the `rsyslog` service is on the Docker host, not another container...which makes sense.  However, this now means that if you're running Logstash as a Docker container, the _host_ now has a dependency on a _container_.  This seems problematic for dynamic environments.  How does the host _know_ where Logstash is?  Standard DNS name per env?  Use [docker-gen](https://github.com/jwilder/docker-gen#docker-gen)?

In addition, this makes for a strange startup order for new environments:
1. Create new Docker host with `rsyslog` service running.
2. Create Logstash Docker container.
3. Update hosts's `rsyslog` config with Logstash's IP/name...and restart.

This seems awkward, but maybe there's a solution again with [docker-gen](https://github.com/jwilder/docker-gen#docker-gen).

**Comment by hkeeler** [comment]
I think I'm leaning back to the STDOUT -> logspout -> Logstash, even with its limitations.  See https://github.com/cfpb/grasshopper/issues/104#issuecomment-109363659.
