### ISSUE TITLE
Log to STDOUT

### ISSUE THREAD

**Issue by jmarin** [cfpb/grasshopper#104]
Change logging in every project to stdout (centralized logging will be done through Docker containers)

**Comment by hkeeler** [comment]
I'm not-so-sure writing logs to STDOUT is the way to go.  The main issue is that logspout considers each new line as its own log entry.  This is not-so-great for things like stack traces, formatted JSON, and other multi-line content under a single log statement.  I think logging via `syslog` to Logstash's [`syslog` input](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-syslog.html).

In this scenario we'd use the docker [`syslog` driver](https://www.sumologic.com/2015/04/16/new-docker-logging-drivers/) so STDOUT/STDERR would be written there, and then our app code would also setup their logging to write to the same `syslog` as well.

I haven't full thought this through.  Curious to get others' thoughts.

**Comment by hkeeler** [comment]
Couple issues with the Docker syslog driver approach.
1. Docker Compose is [_just_](https://github.com/docker/compose/pull/1388) starting to support alternate logging drivers.  In their repo, you can see a [`log_driver`](https://github.com/docker/compose/blob/master/docs/yml.md#log-driver) option, but it doesn't work in the  version of Compose from Homebrew.  The [official docs](https://docs.docker.com/compose/yml/) don't _yet_ mention `log_driver`, but it is in their [repo's docs](https://github.com/docker/compose/blob/master/docs/yml.md#log-driver).
   
   Looks like its in [v1.3.0rc1](https://github.com/docker/compose/releases/tag/1.3.0rc1).  You can install this version via `pip` instead of `brew`.  I will give this a shot in a bit.  Lots of other good stuff in the release as well from the looks of it.
2. Once you switch from the default `json-file` log driver, you lose `docker logs` (and `docker-compose logs`) and the [`/containers/(id)/logs`](http://docs.docker.com/reference/api/docker_remote_api_v1.18/#get-container-logs) Docker Remote API endpoint.  Losing the nicely color-coded logging for `docker-compose` would be a bummer, but isn't necessarily awful.  However, I'm not sure if other pieces of our puzzle (Mesos/Marathon/???) take advantage of the default behavior.

CC: @rosskarchner, @ssayre as I believe they're about to take on Docker logging funtime soon as well.

**Comment by hkeeler** [comment]
Getting Compose running via `pip install` has _issues_.  If you:

```
> brew uninstall docker-compose
> pip install -U docker-compose==1.3.0rc1
```

all appears to go as planned.  However, once you try to _use_  `docker-compose`, you'll get:

```
SSL error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
```

You can check out the following if you want the gory details:
- https://github.com/docker/compose/issues/890
- https://github.com/Homebrew/homebrew/issues/38226

Lots of folks seemed to get this work by _downgrading_ their version of `openssl`, but that seemed like a "bad idea".  I did try the suggested:

```
> brew reinstall openssl python
```

but it was no help.  However, what _did_ fix it was:

```
> pip install requests[security]
```

as suggested on https://github.com/Homebrew/homebrew/issues/38226#issuecomment-108939511.

Of course, once you get that fixed, `docker-compose` may give you a:

```
client and server don't have same version (client : 1.18, server: 1.17)
```

This is at least easily fixed with a:

```
> boot2docker upgrade
```

Hope this helps.

**Comment by jmarin** [comment]
Done
