### ISSUE TITLE
Add missing fields to Point Data Spec

### ISSUE THREAD

**Issue by jmarin** [cfpb/grasshopper#28]
Missing fields from ES schema #23

Authoritative source of the data. String for now (i.e. source = "Census"), explore number based data dictionary

**Comment by hkeeler** [comment]
@jmarin, starting to look into one, but not _exactly_ sure how to proceed.  The `/addresses/points` endpoint currently returns an array of [`FeatureFormat`](https://github.com/jmarin/scale/blob/master/io/geojson/src/main/scala/FeatureJsonProtocol.scala#L12) JSON

``` json
[{
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [-77.0590232, 38.9072597, 0.0]
  },
  "properties": {
    "address": "1311 30th St NW Washington DC 20007"
  }
}]
```

Per the [Address Point API Spec](https://github.com/cfpb/grasshopper/blob/master/docs/point_api_spec.md#address-point-api-spec), we have the following format:

``` json
{
    "type": "Feature",
    "geometry": {
        "type": "Point",
        "coordinates": [
            -94.15513718509897,
            36.48036108322251
        ]
    },
    "properties": {
        "address": "16410 N AR 94 Hwy Pea Ridge 72751 AR",
        "alt_address": "",
        "load_date": 1426878172094
    }
}
```

It looks like the only additional fields are `alt_address` and `load_date`.  Are these the fields you'd like added?  Did we decide to hold off on `alt_address`?

You also mention:

> Authoritative source of the data. String for now (i.e. source = "Census"), explore number based data dictionary.

Does this mean an additional `source` field under `properties`?  Do you see that more as _who_ ("U.S. Census Bureau") we got the data from, or more geared towards the _dataset_ ("U.S. Census Bureau - TIGER/Line")...or should we split this up into two new fields `source` and `dataset`.

Also, these fields all reside under the `properties` field, which shouldn't require any coding changes (as far as I can tell).  Is this issue just be for writing the tests for supporting these new properties?

CC: @wpears since [grasshopper-loader](https://github.com/cfpb/grasshopper-loader) will have to handle any fields we add/modify.

**Comment by hkeeler** [comment]
I've attempted to add `source` and `loadDate` fields as part of the test suite:

``` diff
@@ -29,16 +27,26 @@ class AddressPointServiceSpec extends FlatSpec with MustMatchers with ScalatestR

   val client = server.client

-  private def getPointFeature() = {
+  private def getPointFeature1() = {
     val p = Point(-77.0590232, 38.9072597)
-    val props = Map("geometry" -> p, "address" -> "1311 30th St NW Washington DC 20007")
+    val props = Map(
+      "geometry" -> p,
+      "address" -> "1311 30th St NW Washington DC 20007",
+      "source" -> "U.S. Census Bureau - TIGER/Line",
+      "loadDate" -> "2015-04-16T20:39:23.711Z"
+    )
     val schema = Schema(List(Field("geometry", GeometryType()), Field("address", StringType())))
     Feature(schema, props)
   }
```

...but the test is failing with the following (reformatted for readability):

```
[info] - should geocode a single point *** FAILED ***
[info]   Feature(4326,Schema(
            WrappedArray(
              Field(geometry,GeometryType()), 
              Field(address,StringType()), 
              Field(source,StringType()), 
              Field(loadDate,StringType()))),
            Map(
              geometry -> Point(POINT (-77.0590232 38.9072597)), 
              address -> 1311 30th St NW Washington DC 20007, 
              source -> U.S. Census Bureau - TIGER/Line, 
              loadDate -> 2015-04-16T20:39:23.711Z))

         was not equal to:

         Feature(4326,Schema(
           List(
             Field(geometry,GeometryType()), 
             Field(address,StringType()))),
           Map(
             geometry -> Point(POINT (-77.0590232 38.9072597)), 
             address -> 1311 30th St NW Washington DC 20007, 
             source -> U.S. Census Bureau - TIGER/Line, 
             loadDate -> 2015-04-16T20:39:23.711Z))
```

At first I suspected it was the `WrappedArray` vs. `List`, but that doesn't seem to be the case since this does not fail when there is just a single field under `properties`...in this case `address`.  The _real_ issue is that the `Feature` read from the JSON in ES has `source` and `loadDate` in the `Map`, but the `Feature` built by hand in `getFeaturePoint1()` does not.  I suspect this is a bug in `FeatureJsonProtocol.FeatureFormat`, probably a difference between the `read()` and `write()` functions, but I have not yet confirmed this.

@jmarin, do you want me to dig deeper into this, or do you want to check out `FeatureJsonProtocol`?

**Comment by hkeeler** [comment]
Scratch that.  I wasn't adding the new fields to `schema`.  Now that I've added those as well, it is much closer, but still failing the test:

```
Feature(4326,Schema(WrappedArray(Field(geometry,GeometryType()), Field(address,StringType()), Field(source,StringType()), Field(loadDate,StringType()))),Map(geometry -> Point(POINT (-77.0590232 38.9072597)), address -> 1311 30th St NW Washington DC 20007, source -> U.S. Census Bureau - TIGER/Line, loadDate -> 2015-04-16T20:39:23.711Z))
was not equal to
Feature(4326,Schema(        List(Field(geometry,GeometryType()), Field(address,StringType()), Field(source,StringType()), Field(loadData,StringType()))),Map(geometry -> Point(POINT (-77.0590232 38.9072597)), address -> 1311 30th St NW Washington DC 20007, source -> U.S. Census Bureau - TIGER/Line, loadDate -> 2015-04-16T20:39:23.711Z))
```

The only difference I see is `WrappedArray` vs `List`, which I'm not sure why it would fail on that considering it _doesn't_ fail when `address` is the only `property`.

**Comment by jmarin** [comment]
@hkeeler Do you have this in a branch that I can look at?

**Comment by hkeeler** [comment]
@jmarin, yes I do: https://github.com/cfpb/grasshopper/compare/master...hkeeler:expand-point-api-schema.

But, no need to look at it since I figured out the issue.  Just a stupid typo: `loadData` instead of `loadDate`.  Now that they match in `props` and `schema`, all is well.

I'll hold off on creating a PR until we work out exactly which fields we're going to add, and it all matches up with what @wpears is pushing into Elasticsearch.

Sorry for unnecessary confusion.

**Comment by jmarin** [comment]
@hkeeler No worries, awesome that you figured it out.
