### ISSUE TITLE
Versioned geocoding vs. logs

### ISSUE THREAD

**Issue by wpears** [cfpb/grasshopper#3]
So the core difficulty of the geocoder in my mind will be providing versioning/time-sensitive capabilities. As I understand it, this capability is important because we need a way to verify the return value of a geocode operation done at a given time.

So, alternatively to providing some sort of temporal hierarchy within elasticsearch, what is the downside to just having fine-grained logs on the returns of calls to the geocoder?

If someone is claims they got a different value in some past state of the geocoder, rather than requiring time-sensitive queries, we could just search our logs for their query. In the logged result we'll see what the past return value was... so in this way we could allow verify the output of the geocoder without having to introduce the time complexity to its code base.

Thoughts? Do we want _anyone_ to be able to verify geocoder returns by date or is this something that needs to be done internally?

**Comment by hkeeler** [comment]
Good question.  I think it probably depends on the true purpose/value of returning historical geocodes.  Is it purely for resolving disputes related to geocode conflicts, or is there greater utility?  Also, are we assuming that they are only using the history to check _our_ history, or would they be using it to check against results they'd received from other geocoders.

Searching the logs seems dicey.  We're not requiring an API key, so how would we identify _their_ search?  We _could_ query the logs for the address (assuming the logs will also be in Elasticsearch), and return the resulting JSON if found, but could they game this system?  What if a user requests large batches of addresses just to see if _anyone_ has done a searches on those address?

**Comment by hkeeler** [comment]
Also, are we planning on returning **why** a geocode changed?
1. Data source updated
2. Data source changed (ex: from TIGER to Arkansas state data)

And if yes, do we need to report back the actual data source a temporal geocode came from?

**Comment by jmarin** [comment]
@wpears The idea is intriguing, but as @hkeeler has commented it has some problems. Also, doing what you suggest would require for us to treat logs as a source of truth, i.e. make them persistent forever and put in place the architecture necessary for not losing any log entry. This is hard to do with generic solutions. Having said that, we will need to discuss what we mean by _versioniong_ exactly. We can think of a transaction log for every geocode operation performed. It might also be the case that we only care about versioned geocodes for those entities that are under regulation, and not a generic user (how we differentiate those without API key is up for discussion; most likely wouldn't be at this level and the responsibility of another service).

@hkeeler I don't think we have flushed out the details that you are asking about yet, so answer to your question is that we haven't planned to return why a geocode has changed, but it's something that we will probably need to discuss at some point. As for returning which data source the geocode came from, we might not be able to do that depending on licenses and terms of the data source. Otherwise I'd be in favor of returning it (or a proxy such as "quality" to identify how "good" the source data is).

**Comment by wpears** [comment]
So re: identification/API keys, we haven't talked about how we are confirming/authenticating FIs from Panel, would part of that process be registration of the registration be the generation of an API key that we use both for data intake and to stratify geocodes into versioned / non-versioned (if that is a goal)?

**Comment by jmarin** [comment]
I am closing this issue for now. The requirement is not clear at this point, affects only a subset of users will probably be taken care of outside of this system
