### ISSUE TITLE
Add nginx proxy to docker container

### ISSUE THREAD

**Issue by jmarin** [cfpb/grasshopper#90]
Provide CORS headers

**Comment by hkeeler** [comment]
Just want to make sure I'm going down the right path here.  Docker is geared towards running a single process-per-container.  The current [`addresspoint/Dockerfile`](https://github.com/cfpb/grasshopper/blob/master/addresspoints/Dockerfile) already runs a JVM process.  So, if we want Nginx to sit in front of those requests (to handle CORS headers), we either need to:
1. Hide the JVM and Nginx processes behind another processes.  Looks like [`supervisor`](https://docs.docker.com/articles/using_supervisord/) is the preferred option for this.
2. Add a second Nginx-only `Dockerfile`, and proxy requests from that container to the `addresspoint` container.

Option no. 1 seems nice since you only need a single container.  However, it does add complexity.  I'm also not sure from a Docker/Mesos perspective how easily you can determine the state of your process when `supervisord` is sitting in front of it.  I assume we _want_ the container to stop when the underlying process has issues?  Seems like we're losing something by going the `supervisord` route.

It also seems like option no. 2 is closer to what we'll have in the future when the `addresspoint` API isn't called directly, but instead has a "course-grained" API sitting in front, and you'd just need a single Nginx sitting in front, and all "fine-grained" APIs could be exposed as just the bare JVM processes.

@jmarin and @wpears, thoughts?

**Comment by hkeeler** [comment]
[Docker Compose](https://docs.docker.com/compose/) also looks interesting for managing multiple containers from a single configuration.  Seems useful for dev envs, anyway.

**Comment by hkeeler** [comment]
We decided to skips the CORS setup for now, and go with a merged grasshopper and addresspoints site.  This can be followed under https://github.com/cfpb/grasshopper-ui/pull/50.

Closing this issue.
